POST http://admin@financer.com:123456@localhost:8080/transactions
Content-Type: application/json

{
  "type": "expense",
  "amount": 100.00,
  "category": "food",
  "description": "Almoço"
}

###

GET http://admin@financer.com:123456@localhost:8080/transactions

###


POST http://user:64f38f59-d6c7-49f5-8165-688de784f041@localhost:8080/transactions
Content-Type: application/json

{
  "type": "expense",
  "amount": -50,
  "category": "transport",
  "description": "Uber"
}